-- ============================================================
-- Research Management System - Supabase / PostgreSQL Schema
-- Run this in the Supabase SQL Editor to set up the database.
-- ============================================================

-- ============================================================
-- TABLES
-- ============================================================

-- Users (login accounts; password is a bcrypt hash stored by the app)
CREATE TABLE IF NOT EXISTS users (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username    TEXT NOT NULL UNIQUE,
  password    TEXT NOT NULL,
  full_name   TEXT NOT NULL,
  role        TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Academic programs
CREATE TABLE IF NOT EXISTS programs (
  id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  code        TEXT NOT NULL UNIQUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Research papers / theses / capstone projects (unified as research)
CREATE TABLE IF NOT EXISTS research (
  id            BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  code          TEXT NOT NULL UNIQUE,            -- generated by app: e.g. RS-2026-0001
  title         TEXT NOT NULL,
  authors       TEXT NOT NULL,                   -- comma-separated author names
  adviser       TEXT,
  program_id    BIGINT REFERENCES programs(id) ON DELETE SET NULL,
  year          INTEGER NOT NULL,
  abstract      TEXT NOT NULL DEFAULT '',
  keywords      TEXT NOT NULL DEFAULT '',        -- comma-separated keywords
  submitted_by  BIGINT REFERENCES users(id),
  status        TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('approved', 'pending', 'rejected')),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes used by the search / filter queries
CREATE INDEX IF NOT EXISTS idx_research_status    ON research (status);
CREATE INDEX IF NOT EXISTS idx_research_year      ON research (year);
CREATE INDEX IF NOT EXISTS idx_research_program   ON research (program_id);
CREATE INDEX IF NOT EXISTS idx_users_role         ON users (role);

-- ============================================================
-- SEED DATA  (mirrors server/data/*.json defaults)
-- ============================================================

-- Default admin account: admin / admin123 (bcrypt hash matches existing seed)
INSERT INTO users (id, username, password, full_name, role, created_at) OVERRIDING SYSTEM VALUE
VALUES (1, 'admin', '$2a$10$dDYTMkTJV82aMnS98qKZ3.EPcKTkMkFyjiILbJGSGzYgvMbEF9eKS', 'System Administrator', 'admin', now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO programs (id, name, code, created_at) OVERRIDING SYSTEM VALUE
VALUES
  (1, 'Computer Science', 'CS', now()),
  (2, 'Information Technology', 'IT', now()),
  (3, 'Information Systems', 'IS', now()),
  (4, 'Computer Engineering', 'CPE', now())
ON CONFLICT (id) DO NOTHING;

-- ============================================================
-- NOTE: Row Level Security
-- The app authenticates with the service-role key, which bypasses RLS.
-- If you expose queries through a client with the anon key instead,
-- you must enable RLS and add policies on every table.
-- ============================================================